// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaB9pmGRCJYRNQTsN4DvHyNxvQHMpEKoA',
    appId: '1:1002808551000:web:14307ed265bded7a8ecc2d',
    messagingSenderId: '1002808551000',
    projectId: 'mba-kurir',
    authDomain: 'mba-kurir.firebaseapp.com',
    storageBucket: 'mba-kurir.appspot.com',
    measurementId: 'G-P06J99RWCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtzvUVr3wDElZJunenGVpwYjdburX1x6U',
    appId: '1:1002808551000:android:f801268216fdd8488ecc2d',
    messagingSenderId: '1002808551000',
    projectId: 'mba-kurir',
    storageBucket: 'mba-kurir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH2q-RZ93F9AL49jT2Rm1gk7Q2YNArg8I',
    appId: '1:1002808551000:ios:e5b1a8ec21a8fbc58ecc2d',
    messagingSenderId: '1002808551000',
    projectId: 'mba-kurir',
    storageBucket: 'mba-kurir.appspot.com',
    iosClientId: '1002808551000-s2m6lhg10f0fvbu4aaaacv24v9lsn5hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mbakurir',
  );
}
